version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

  flask_app:
    container_name: Anton
    build: ./flask_app
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db/mydatabase

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - flask_app

